#! /bin/sh

# clone-flexdll
#
# Brings in flexdll, if necessary

if [ -d "flexdll" ] && [ -f "flexdll/flexdll.c" ]; then
    echo "[Flexdll] Already present, no need to clone."
else
    echo "[Flexdll] Cloning..."
    git clone https://github.com/esy-ocaml/flexdll.git
    cd flexdll
    git checkout b6b231493387a7628103dc744b3bcd3d413c80d9
    cd ..
    echo "[Flexdll] Clone successful!"
fi
