#! /bin/sh

# esy-build
#
# Wrapper to execute appropriate build strategy, based on platform

case "$(uname -s)" in
    CYGWIN*|MINGW32*|MSYS*)
        echo "[esy-build] Detected windows environment..."
        make -j1 world.opt
        make flexlink.opt
        ;;
    *)
        echo "[esy-build] Detected OSX / Linux environment"
        make -j world.opt
        ;;
esac

# Common build steps
make install
make clean
