#! /bin/bash

# esy-build
#
# Wrapper to execute appropriate build strategy, based on platform

set -u
set -e
set -o pipefail

case "$(uname -s)" in
    CYGWIN*|MINGW32*|MSYS*)
        echo "[esy-build] Detected windows environment..."
        make world.opt
        make flexlink.opt
	make install
	echo "Remove bytecode binaries.."
	rm $cur__install/bin/*.opt.exe
	rm $cur__install/bin/*.byte.exe
	echo "Done"
        ;;
    *)
        echo "[esy-build] Detected OSX / Linux environment"
        make -j4 world.opt
	make install
	echo "Remove bytecode binaries.."
	rm $cur__install/bin/*.byte
	echo "Done"
        ;;
esac

